language: minimal

dist: xenial

addons:
  apt:
    packages:
      - docker-ce

install:
  - docker version

stages:
  - precommit
  - tests

jobs:
  include:
    - stage: precommit
      name: "Pre-commit Check"
      script:
      - docker run --rm -it -v $PWD:/work -w /work python:3.6 bash -c "pip3 install -r requirements-dev.txt; pre-commit run --files $(find ftlib test -name '*.py' -print0 | tr '\0' ' ')"
    - stage: tests
      name: "Tests"
      script:
        - set -e
        - bash scripts/setup_k8s_env.sh
        - docker build -t ftlib:deploy -f deploy/Dockerfile .
        - docker run --rm -it -v $PWD:/work -w /work ftlib:deploy bash -c 'python3 -c "import ftlib"'
        - kubectl apply -f deploy/ftlib-rbac.yaml
        # TODO: Validate the result of the created deployment
        - kubectl apply -f deploy/ftlib-test.yaml

# Only build on this list of branches
branches:
  only:
  - master
