FROM dockerhub.azk8s.cn/nvidia/cuda:10.1-devel-ubuntu18.04

RUN sed -i "s@http://.*archive.ubuntu.com@http://mirrors.huaweicloud.com@g" /etc/apt/sources.list && \
    sed -i "s@http://.*security.ubuntu.com@http://mirrors.huaweicloud.com@g" /etc/apt/sources.list && \
    apt update && apt -y install wget cmake

RUN wget -O miniconda.sh https://mirrors.tuna.tsinghua.edu.cn/anaconda/miniconda/Miniconda3-py38_4.8.2-Linux-x86_64.sh && \
    bash miniconda.sh -b && rm miniconda.sh

ENV PATH=/root/miniconda3/bin:${PATH}

RUN conda init bash && echo "auto_activate_base: true" > ~/.condarc

RUN pip install -i https://pypi.tuna.tsinghua.edu.cn/simple pytest pybind11==2.4.3 numpy

RUN wget -O /usr/share/cmake-3.10/Modules/FindNCCL.cmake https://raw.githubusercontent.com/BVLC/caffe/master/cmake/Modules/FindNCCL.cmake

RUN wget -O pybind11.tar.gz https://github.com/pybind/pybind11/archive/v2.4.3.tar.gz && \
    tar -xf ./pybind11.tar.gz && cd pybind11-2.4.3 && mkdir build && cd build && \
    cmake .. && make -j4 && make install && cd ../.. && rm -rf ./pybind11*

COPY . /root/nccl/

RUN cd /root/nccl && ls && mkdir build && cd build && cmake .. && make -j4
